factors=[0,1,20]
name=[[50,"raz"],"Nabeel","Aman"]
mixed=[10,"Sarfaraz",True]
print(factors,name,mixed)
print(factors[2])
print(mixed[2])
print(len(mixed))
print(len(name))
print(len(factors))
print(name[0])
print(name[0][1][0:2])